title: <p align="center"> Muskaan Gabra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="/pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/YOUR_LINKEDIN">LinkedIn</a> |
  <a href="https://github.com/YOUR_GITHUB">GitHub</a>
  <br><br>
  Passionate about Data Science, Generative AI, and Software Engineering.  
  Skilled in building scalable pipelines, AI assistants, and automation solutions.  
  </p>

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
